import type { MusicPackDefinition } from "../game/types";

export const MUSIC_PACK_MANIFEST: MusicPackDefinition[] = [
  {
    id: "sunset-vector",
    name: "Sunset Vector",
    theme: "Bright synth-pop cruise",
    accent: "#ffd36d",
    description:
      "A golden-hour lead line with enough lift to sell the opening coast road immediately.",
    previewCue: "Warm pads, bright lead, postcard optimism.",
    rootHz: 220,
    bpm: 118,
    routeMood: {
      harbor: "Keeps the harbor branch playful and expensive.",
      neon: "Turns the expressway into a glamorous late-summer sprint.",
    },
    sections: {
      cruise: {
        id: "sunset-vector-cruise",
        label: "Coastline cruise",
        leadPattern: [12, 14, 16, 19, 16, 14, 12, 9],
        bassPattern: [0, 0, 5, 5, 7, 7, 5, 3],
        padPattern: [0, 7, 5, 9],
        accentPattern: [24, 24, 0, 24],
      },
      branch: {
        id: "sunset-vector-branch",
        label: "Split commitment",
        leadPattern: [16, 19, 21, 19, 16, 14, 12, 14],
        bassPattern: [0, 5, 7, 5, 3, 0, 5, 7],
        padPattern: [0, 5, 9, 7],
        accentPattern: [24, 0, 24, 28],
      },
      finish: {
        id: "sunset-vector-finish",
        label: "Skyline arrival",
        leadPattern: [21, 19, 16, 24, 21, 19, 16, 14],
        bassPattern: [0, 7, 5, 9, 7, 5, 3, 0],
        padPattern: [0, 9, 7, 5],
        accentPattern: [28, 31, 28, 24],
      },
    },
    checkpointSting: [12, 19],
    lowTimeSting: [7, 3],
    finishSting: [12, 16, 19, 24],
    unlockRule: {
      type: "default",
      label: "Available from the first run.",
    },
  },
  {
    id: "slipstream-serenade",
    name: "Slipstream Serenade",
    theme: "Palm-lined fusion pulse",
    accent: "#70f7d3",
    description:
      "More rhythmic and playful, tuned for traffic weaving and that first checkpoint rush.",
    previewCue: "Percussive bass pulse and a breezy lead figure.",
    rootHz: 196,
    bpm: 124,
    routeMood: {
      harbor: "Pairs especially well with the low-road dock rhythm.",
      neon: "Adds a little lounge confidence to the skyline rush.",
    },
    sections: {
      cruise: {
        id: "slipstream-serenade-cruise",
        label: "Palm boulevard",
        leadPattern: [7, 10, 12, 14, 12, 10, 7, 5],
        bassPattern: [0, 3, 5, 3, 0, 3, 7, 5],
        padPattern: [0, 5, 3, 7],
        accentPattern: [19, 0, 17, 0],
      },
      branch: {
        id: "slipstream-serenade-branch",
        label: "Harbor rhythm",
        leadPattern: [12, 14, 15, 17, 15, 14, 12, 10],
        bassPattern: [0, 5, 3, 7, 5, 3, 0, 3],
        padPattern: [0, 3, 7, 10],
        accentPattern: [19, 22, 19, 17],
      },
      finish: {
        id: "slipstream-serenade-finish",
        label: "Festival lights",
        leadPattern: [15, 17, 19, 22, 19, 17, 15, 12],
        bassPattern: [0, 7, 5, 10, 7, 5, 3, 0],
        padPattern: [0, 7, 10, 5],
        accentPattern: [24, 22, 19, 17],
      },
    },
    checkpointSting: [10, 14],
    lowTimeSting: [5, 2],
    finishSting: [12, 15, 19, 22],
    unlockRule: {
      type: "default",
      label: "Available from the first run.",
    },
  },
  {
    id: "night-circuit",
    name: "Night Circuit",
    theme: "Neon skyline runner",
    accent: "#98a7ff",
    description:
      "A darker expressway groove for the city branch, with a cooler low end and cleaner attack.",
    previewCue: "Cold bassline, glassy lead, late-night momentum.",
    rootHz: 246.94,
    bpm: 132,
    routeMood: {
      harbor: "Makes the docks feel tense and expensive.",
      neon: "The intended soundtrack for the elevated neon charge.",
    },
    sections: {
      cruise: {
        id: "night-circuit-cruise",
        label: "Blue-hour glide",
        leadPattern: [0, 3, 7, 10, 12, 10, 7, 3],
        bassPattern: [0, -2, 3, -2, 5, 3, -2, -5],
        padPattern: [0, 3, 7, 10],
        accentPattern: [19, 19, 22, 0],
      },
      branch: {
        id: "night-circuit-branch",
        label: "Expressway lock-in",
        leadPattern: [7, 10, 12, 15, 12, 10, 7, 5],
        bassPattern: [0, 3, 7, 3, 10, 7, 3, 0],
        padPattern: [0, 7, 10, 12],
        accentPattern: [24, 0, 24, 27],
      },
      finish: {
        id: "night-circuit-finish",
        label: "Skyline charge",
        leadPattern: [12, 15, 19, 22, 24, 22, 19, 15],
        bassPattern: [0, 7, 10, 7, 12, 10, 7, 3],
        padPattern: [0, 10, 12, 7],
        accentPattern: [27, 31, 27, 24],
      },
    },
    checkpointSting: [12, 15],
    lowTimeSting: [3, 0],
    finishSting: [12, 19, 24, 27],
    unlockRule: {
      type: "score",
      value: 2400,
      label: "Intended unlock after a strong first complete run.",
    },
  },
];
