import type { ScenicSegment } from "../game/types";

export const STAGE_MANIFEST: ScenicSegment[] = [
  {
    id: "azure-coast",
    label: "Azure Coast",
    description: "Sunset cliffs, palms, and warm ocean glare.",
    biome: "coast",
    scenery: "palms",
    start: 0,
    end: 2600,
    trafficDensity: 0.55,
    trafficDensityCurve: [0.42, 0.58, 0.68],
    skyline: 0.18,
    nightLevel: 0.08,
    horizonLift: 0.01,
    billboardSet: "festival-posters",
    weatherModifier: "sea-breeze",
    checkpointTarget: 14,
    eventBannerPool: ["dispatch-intro", "cassette-reminder"],
    destinationPostcardText:
      "Azure Coast opens like a brochure: orange sea light, palms, and a horizon that already promises a city worth chasing.",
    palette: {
      skyTop: "#183067",
      skyMid: "#ff8a68",
      skyBottom: "#ffd494",
      sun: "#ffd66b",
      glow: "#ffb26a",
      farSilhouette: "#526f9a",
      nearSilhouette: "#1b3557",
      sea: "#2e75ad",
      ground: "#142335",
      road: "#4d5965",
      lane: "#f1f1ee",
      shoulder: "#c6ae78",
      curbA: "#fff2d8",
      curbB: "#d7484a",
      roadsidePrimary: "#38b879",
      roadsideSecondary: "#2a8f61",
      cityLight: "#ffe2a3",
      fog: "#f8c8a0",
    },
  },
  {
    id: "mirage-causeway",
    label: "Mirage Causeway",
    description: "Long bridge spans, sodium lamps, and the first skyline hints.",
    biome: "causeway",
    scenery: "causeway",
    start: 2600,
    end: 5050,
    trafficDensity: 0.72,
    trafficDensityCurve: [0.68, 0.76, 0.82],
    skyline: 0.34,
    nightLevel: 0.35,
    horizonLift: 0.02,
    billboardSet: "causeway-signage",
    weatherModifier: "clear",
    checkpointTarget: 13,
    eventBannerPool: ["rival-checkin", "route-split-warning"],
    destinationPostcardText:
      "The causeway is the promise shot: a bridge of sodium lamps with Mirador City beginning to glow in the distance.",
    palette: {
      skyTop: "#16264c",
      skyMid: "#935a87",
      skyBottom: "#f8b36c",
      sun: "#ffd6a0",
      glow: "#ff9c6f",
      farSilhouette: "#516181",
      nearSilhouette: "#182339",
      sea: "#1f4569",
      ground: "#111929",
      road: "#505763",
      lane: "#f4f1e9",
      shoulder: "#9c9d9d",
      curbA: "#ecf0ff",
      curbB: "#e1525a",
      roadsidePrimary: "#ffd486",
      roadsideSecondary: "#84d7ff",
      cityLight: "#ffe8af",
      fog: "#a790ba",
    },
  },
  {
    id: "harbor-slip",
    label: "Harbor Slip",
    description: "Dock cranes, warehouse strips, and stacked brake lights.",
    biome: "harbor",
    scenery: "harbor",
    start: 5050,
    end: 7100,
    trafficDensity: 0.88,
    trafficDensityCurve: [0.84, 0.92, 0.86],
    skyline: 0.52,
    nightLevel: 0.62,
    horizonLift: 0.025,
    billboardSet: "port-logistics",
    weatherModifier: "harbor-haze",
    checkpointTarget: 12,
    eventBannerPool: ["harbor-scenic", "rival-harbor"],
    destinationPostcardText:
      "Harbor Slip feels industrial and alive: cranes cut across the skyline while brake lights stack under the docks.",
    palette: {
      skyTop: "#0d1937",
      skyMid: "#214567",
      skyBottom: "#db9156",
      sun: "#f8b86d",
      glow: "#ff874f",
      farSilhouette: "#334a67",
      nearSilhouette: "#101b2d",
      sea: "#0d2946",
      ground: "#0c1524",
      road: "#454d57",
      lane: "#f3ede4",
      shoulder: "#6a7885",
      curbA: "#f2f6ff",
      curbB: "#ff6d63",
      roadsidePrimary: "#7fe3ef",
      roadsideSecondary: "#ffb45f",
      cityLight: "#ffd38b",
      fog: "#4f6d88",
    },
  },
  {
    id: "neon-express",
    label: "Neon Express",
    description: "Elevated ribbon roads with billboard light and city glow.",
    biome: "metro",
    scenery: "neon",
    start: 5050,
    end: 7100,
    trafficDensity: 0.76,
    trafficDensityCurve: [0.66, 0.74, 0.82],
    skyline: 0.75,
    nightLevel: 0.92,
    horizonLift: 0.035,
    billboardSet: "luxury-neon",
    weatherModifier: "neon-mist",
    checkpointTarget: 12,
    eventBannerPool: ["neon-scenic", "rival-neon"],
    destinationPostcardText:
      "Neon Express is the premium fantasy: elevated ribbon roads, cold signage, and a skyline that feels close enough to touch.",
    palette: {
      skyTop: "#071125",
      skyMid: "#1a2558",
      skyBottom: "#6a3976",
      sun: "#ff76c5",
      glow: "#6e8cff",
      farSilhouette: "#29406d",
      nearSilhouette: "#09101d",
      sea: "#111b33",
      ground: "#070d17",
      road: "#3f4652",
      lane: "#f5f2ff",
      shoulder: "#52608b",
      curbA: "#dfe9ff",
      curbB: "#ff5aa5",
      roadsidePrimary: "#78d7ff",
      roadsideSecondary: "#ff83d2",
      cityLight: "#9de5ff",
      fog: "#303d74",
    },
  },
  {
    id: "marina-underpass",
    label: "Marina Underpass",
    description: "Ferry windows, service tunnels, and warm dockside afterglow.",
    biome: "harbor",
    scenery: "harbor",
    start: 5050,
    end: 7100,
    trafficDensity: 0.84,
    trafficDensityCurve: [0.8, 0.88, 0.83],
    skyline: 0.48,
    nightLevel: 0.68,
    horizonLift: 0.02,
    billboardSet: "marina-afterparty",
    weatherModifier: "harbor-haze",
    checkpointTarget: 12,
    eventBannerPool: ["afterglow-marina-scenic", "afterglow-marina-rival"],
    destinationPostcardText:
      "Marina Underpass trades big-crane drama for ferries, service tunnels, and warm reflections under the hillside roads.",
    palette: {
      skyTop: "#101d3b",
      skyMid: "#244664",
      skyBottom: "#e59a5b",
      sun: "#ffc57b",
      glow: "#ff9460",
      farSilhouette: "#36516f",
      nearSilhouette: "#111b2c",
      sea: "#12304d",
      ground: "#0d1624",
      road: "#474f59",
      lane: "#f5efe5",
      shoulder: "#778391",
      curbA: "#f4f7ff",
      curbB: "#ff7a62",
      roadsidePrimary: "#84efd0",
      roadsideSecondary: "#ffc07a",
      cityLight: "#ffe1a0",
      fog: "#5c748c",
    },
  },
  {
    id: "crown-vista",
    label: "Crown Vista",
    description: "Terrace ramps, rooftop glass, and a colder hilltop climb.",
    biome: "metro",
    scenery: "neon",
    start: 5050,
    end: 7100,
    trafficDensity: 0.72,
    trafficDensityCurve: [0.64, 0.72, 0.8],
    skyline: 0.82,
    nightLevel: 0.94,
    horizonLift: 0.04,
    billboardSet: "crown-overlook",
    weatherModifier: "neon-mist",
    checkpointTarget: 12,
    eventBannerPool: ["afterglow-crown-scenic", "afterglow-crown-rival"],
    destinationPostcardText:
      "Crown Vista is the hilltop fantasy: terrace ramps, rooftop glass, and the observatory ring burning through the mist ahead.",
    palette: {
      skyTop: "#08111f",
      skyMid: "#16274c",
      skyBottom: "#7f5a4a",
      sun: "#ffd27b",
      glow: "#8bbfff",
      farSilhouette: "#2b4268",
      nearSilhouette: "#08111b",
      sea: "#111a2f",
      ground: "#060d16",
      road: "#414754",
      lane: "#f7f4ef",
      shoulder: "#627097",
      curbA: "#edf4ff",
      curbB: "#ff9068",
      roadsidePrimary: "#84dfff",
      roadsideSecondary: "#ffd27b",
      cityLight: "#b6efff",
      fog: "#36486f",
    },
  },
  {
    id: "skyline-finish",
    label: "Skyline Finish",
    description: "The final rush under towers and reflected glass.",
    biome: "metro",
    scenery: "neon",
    start: 7100,
    end: 9200,
    trafficDensity: 0.82,
    trafficDensityCurve: [0.78, 0.84, 0.8],
    skyline: 0.96,
    nightLevel: 1,
    horizonLift: 0.04,
    billboardSet: "skyline-festival",
    weatherModifier: "clear",
    checkpointTarget: 11,
    eventBannerPool: ["final-approach"],
    destinationPostcardText:
      "Mirador Skyline closes the run with tower reflections, festival light, and just enough traffic to keep the city feeling alive.",
    palette: {
      skyTop: "#050b16",
      skyMid: "#101c40",
      skyBottom: "#4f2b67",
      sun: "#80f0ff",
      glow: "#8f86ff",
      farSilhouette: "#1f345f",
      nearSilhouette: "#060b14",
      sea: "#0c1320",
      ground: "#050912",
      road: "#3e4451",
      lane: "#f5f2ff",
      shoulder: "#586491",
      curbA: "#ffffff",
      curbB: "#ff4f9d",
      roadsidePrimary: "#81e8ff",
      roadsideSecondary: "#ff9ed9",
      cityLight: "#9ff0ff",
      fog: "#222e56",
    },
  },
  {
    id: "afterglow-heights",
    label: "Afterglow Heights",
    description: "The final ascent through hilltop terraces and observatory light.",
    biome: "metro",
    scenery: "neon",
    start: 7100,
    end: 9200,
    trafficDensity: 0.78,
    trafficDensityCurve: [0.72, 0.8, 0.76],
    skyline: 0.9,
    nightLevel: 0.98,
    horizonLift: 0.05,
    billboardSet: "heights-afterparty",
    weatherModifier: "clear",
    checkpointTarget: 11,
    eventBannerPool: ["afterglow-final-approach"],
    destinationPostcardText:
      "Afterglow Heights closes the run with terrace lights, observatory glow, and a final climb that feels more celebratory than hostile.",
    palette: {
      skyTop: "#071018",
      skyMid: "#17304e",
      skyBottom: "#8f5d44",
      sun: "#ffe29a",
      glow: "#ffd08b",
      farSilhouette: "#254565",
      nearSilhouette: "#071018",
      sea: "#101926",
      ground: "#060b12",
      road: "#424851",
      lane: "#fbf7ef",
      shoulder: "#6b7395",
      curbA: "#fff8ef",
      curbB: "#ff8b67",
      roadsidePrimary: "#8ee6ff",
      roadsideSecondary: "#ffd38e",
      cityLight: "#fff0c0",
      fog: "#3c4d69",
    },
  },
];
